site:
  distance: 50
plant:
  layout: grid
  row_spacing: 7
  substation_distance: 1
  turbine_spacing: 7
landfall:
  interconnection_distance: 3
  trench_length: 2
# Vessels
oss_install_vessel: example_support_vessel
towing_vessel_groups:
  towing_vessels: 2
  ahts_vessels: 1
  num_groups: 3
# Port characteristics: define in individual port YAMLs

# Module Specific
substructure:
  takt_time: 168
  towing_speed: 7
  unit_cost: 11757583 # USD, IEA VolutrnUS Reference Hull. Output from a run by Garret , Wisdem. 19 Aug 2022.

mooring_system_design:
    num_lines: 3 # int
    anchor_type: "Drag Embedment"

# Configured Phases
design_phases:
- OffshoreSubstationDesign  # SemiTaut Mooring seems to need this
install_phases:
  FloatingSubstationInstallation: 0
