site:
  distance: 50
plant:
  layout: grid
  row_spacing: 7
  substation_distance: 1
  turbine_spacing: 7
landfall:
  interconnection_distance: 3
  trench_length: 2
# Vessels
towing_vessel_groups:
  towing_vessels: 3
  ahts_vessels: 1
  num_groups: 3
array_cable_install_vessel: _shared_pool_:example_array_cable_lay_vessel
export_cable_install_vessel: _shared_pool_:example_export_cable_lay_vessel
oss_install_vessel: example_support_vessel # assume that this is towed out with a anchor handling vessel
# Port characteristics: define in individual port YAMLs

# Module Specific
substructure:
  takt_time: 168
  towing_speed: 5.5
  unit_cost: 11757583 # USD, IEA VolutrnUS Reference Hull. Output from a run by Garret , Wisdem. 19 Aug 2022.

mooring_system_design:
    num_lines: 3 # int
    anchor_type: "Drag Embedment"

array_system_design:
  cables:
   - XLPE_500mm_132kV_dynamic
export_system_design:
  cables: HVDC_2000mm_320kV
  percent_added_length: 0.0
substation_design:
  floating_oss: True

# Configured Phases
design_phases:
- OffshoreSubstationDesign  # SemiTaut Mooring seems to need this
- ArraySystemDesign
- ElectricalDesign
## from ORBIT:
- SemiSubmersibleDesign
- SemiTautMooringSystemDesign
install_phases:
  ArrayCableInstallation: !!python/tuple
  - MooredSubInstallation
  - 0.25 # Start array cable installation when 40% of floaters are installed
  ExportCableInstallation: 0
  MooredSubInstallation: !!python/tuple
  - MooringSystemInstallation
  - 0.4 # Start substructure install when 50% of mooring lines installed
  MooringSystemInstallation: 0
  FloatingSubstationInstallation: !!python/tuple
  - ExportCableInstallation
  - 0.25 # Start OSS installation when 25% of cable installation is complete
