name: Deploy to PyPI

on:
  release:
    types: [published]

jobs:
  release-pypi:
    environment: release-pypi
    # Upload to PyPI on every published release
    if: github.event.action == 'published'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Build package
        run: |
          python -m pip install --upgrade pip
          pip install setuptools build wheel twine
          python -m build
          twine check --strict dist/*
      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          verbose: True
          password: ${{ secrets.PYPI_API_TOKEN }}
